In [10]:
class Student:
    """class info   """
    name = 'Depi'
    age = 5

    def std_info(self):
        print(self)

In [12]:
s1 = Student()
s1.name = "Akram"
s1.age = 21
print(s1.name)
print(s1.age)
print(s1)
print(s1.std_info())


Akram
21
None


In [15]:
class Student:
    def __init__(self, name = "test", age = 5):
        self.name = name
        self.age = age
        self.grade = 0

    def std_info(self):
        return f"my name is {self.name}, my age is {self.age}"

In [23]:
s2 = Student()
s1 = Student("Akram", 21)

s1.std_info()


'my name is Akram, my age is 21'

In [24]:
class calc:
    def __init__(self, x,y):
        self.x = x
        self.y = y

    def add(self):
        return self.x + self.y

In [25]:
c1 = calc(2,3)
c1.add()


5

In [28]:
from abc import ABC, abstractmethod

class Animal(ABC):
    @abstractmethod
    def move(self):
        pass

class Bird(Animal):
    def move(self):
        print("move from Bird")


class Cat(Animal):
    def move(self):
         print("move from Cat")

a = Bird()
a.move()
b = Cat()
b.move()

move from Bird
move from Cat


In [33]:
class Rectangle:
    __length = 5
    width = 10

    def area(self):
        return self.__length * self.width

r = Rectangle()
print(r._Rectangle__length)
print(r.width)
print(r.area())

5
10
50


In [34]:
class Rectangle():
    def __init__(self, length, width):
        self.__length = length
        self.__width = width

    def length(self):
        return self.__length

In [35]:
r = Rectangle(10, 20)
r.__length
r.length

AttributeError: 'Rectangle' object has no attribute '__length'

In [36]:
class Shape:
    def calculate_area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def calculate_area(self):
        return 3.14 * (self.radius)**2

class Square(Shape):
    def __init__(self, side):
        self.side =side

    def calculate_area(self):
        return self.side**2



In [37]:
class dog:
    def speak(self):
        return "Woof"

class cat:
    def speak(self):
        return "Meow"

d1 = dog()
c1 = cat()
print(d1.speak())
print(c1.speak())

Woof
Meow


In [38]:
class Model:

    def fit(self, x,y):
        raise NotImplementedError
    def predict(self, x):
        raise NotImplementedError

class LinearRegression(Model):
    def fit(self, x, y):
        print("fitting linear regression")

    def predict(self,x):
        print("predicting with linear regression")

class DicisionTree(Model):
    def fit(self, x, y):
        print("fitting Decision Tree")

    def predict(self, x):
        print("predicting with Decision Tree")

models = [LinearRegression(), DicisionTree()]
for model in models:
    model.fit(None, None)
    model.predict(None)

fitting linear regression
predicting with linear regression
fitting Decision Tree
predicting with Decision Tree


In [40]:
calc(int)
calc(int, int)
calc(int, int ,int)

TypeError: calc.__init__() missing 1 required positional argument: 'y'

In [43]:
class Calc:
    
    def add(self, a, b=0):
        return a+b

In [ ]:
c1 = Calc()
c1.add(20)

20

: 

In [ ]:
class point:
    def __init__(self):


    def __add__(self, other):
        pass

In [2]:
class student:
    def init_(self, name, age) -> None:
        self.name = name
        self.age = age

    def str_(self):
        return f"my name is {self.name}, my age is {self.age}"



In [4]:
class student:
    def __init__(self,name, age):
        self.name=name
        self.age=age
    def __str__(self):
        return f"my name is {self.name}, age is {self.age}"



In [5]:
s1 = student("akr", 21)
print(s1)

my name is akr, age is 21


In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np

In [ ]:
s = np.array(5)
print(s.ndim)
x = [1,2,3,4]

v = np.array([1,2,3,4,5,6])
print(v)
m = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(m)

5
<class 'list'>
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
print(mat)
vec[:,None]

[[1 2]
 [3 4]
 [5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [24]:
def array_reshape(arr : list, rows:int =-1, cols: int =-1):
    try:
        arr = np.array(arr)
        return arr.reshape(rows,cols)
    except(TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")

In [27]:
vec = [1,2,3,4,5,6]
array_reshape(vec,2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
m = np.array([[1, 2, '3'],
              [4, 5.5, 6],
              [7,8,9]])
print(m.dtype)
fmat = m.astype(float)
print(fmat.dtype)

<U32
float64


In [41]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

matT = mat.T
matT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [43]:
mat = np.zeros((3,4))
mat.astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])