In [1]:
import numpy as np
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [2]:
def init_m(shape, n =0):
    return np.full(shape, n)

In [4]:
init_m((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [6]:
np.arange(0,361,90)

array([  0,  90, 180, 270, 360])

In [34]:
def gen3x3mat(shape, n=8):
    return (n *np.random.random(shape)).astype(int)


In [40]:
x = gen3x3mat((4,3), 43)
print(x)

[[42 22 41]
 [41 23  7]
 [ 5 37 14]
 [33 24 42]]


In [42]:
mat1 = np.ones((3,4))
print(mat1)
print("="*20)
mat2 = np.zeros((5,3))
print(mat2)
np.savez('np_file.npz', cat = mat1, dog = mat2)
 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
with np.load('np_file.npz') as file:
    mat1 = file['cat']
    mat2 = file['dog']
 
print(mat1)
print("="*20)
print(mat2)
 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [46]:
import pandas as pd

In [49]:
s= pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [55]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
df = pd.DataFrame(data, columns= ['id', 'sal', 'dep'])
data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)
type(df)


pandas.DataFrame

In [57]:
cols = ['col1','col2','col3']
df.columns = cols
df

,col1,col2,col3
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [60]:
df.describe()

,col1,col2
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [69]:
cols = ['col1', 'col2']
df[cols] = df[cols].astype("int")
df.dtypes

col1    int64
col2    int64
col3      str
dtype: object

In [70]:
df.describe(include= 'number')

,col1,col2
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [71]:
x = df.col2.idxmax()
x

2

In [72]:
df.info()


<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str  
dtypes: int64(2), str(1)
memory usage: 240.0 bytes


In [75]:
df['col2'].sum()

np.int64(2109)

In [76]:
sort_df = df.sort_values(by = 'col1', ascending= False)
sort_df

,col1,col2,col3
3,4,444,xyz
2,3,666,ghi
1,2,555,def
0,1,444,abc


In [77]:
df['col1'].apply(lambda x : x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [78]:
df.col1.iloc[2]

np.int64(3)

In [85]:
x = df.iloc[:, 0:2]
print(x)
print('='*20)
y = df.iloc[:, -1]
print(y)

   col1  col2
0     1   444
1     2   555
2     3   666
3     4   444
0    abc
1    def
2    ghi
3    xyz
Name: col3, dtype: str
